### ISSUE TITLE
Failed to send system signal to the process

### ISSUE THREAD

**Issue by saranicole** [doitintl/secrets-init#2]
The other issue is resolved however I'm getting a new error:

```
Saras-MBP:deploy sarajarjoura$ kubectl logs -f $POD --all-containers
testing
time="2020-03-30T13:35:59Z" level=error msg="failed to send system signal to the process" args="[sh -c echo $TEST_SECRET]" error="no such process" path=/bin/sh pid=16 signal="urgent I/O condition"
```

Thanks in advance.

**Comment by alexei-led** [comment]
@saranicole few comments:

1. use latest `0.2.6` image or just `latest` (or no tag)
2. if you are running K8s Deployment, make sure it does not exit immediately (like `echo $SECRET`) but continue to run (`echo $SECRET; tail -f /dev/null`). Otherwise, K8s will try to restart this Pod (forever)
3. Consider writing K8s Job for short commands, like `echo`
4. **Important** your Pod must be associated with Cloud IAM role (that has read permissions for the secret), either through Node ServiceAccount or using Workload Identity (with linked K8s Service Account)
5. Probably this is an type error, but the `$PROJECT_ID` must be a real Google project ID (or be defined in a separate env variable)

**Comment by saranicole** [comment]
Ok - yes #2 addressed the issue, the pod was exiting immediately so adding the tail command kept it alive.  Thanks!
